# This workflow uses actions/cache@v3, but it would always get cache miss since it runs on deployment_status trigger
# See - https://github.com/actions/cache/issues/319
# If GitHub would allow deployment_status trigger to access cache, it would work here too
name: Vercel E2E
on:
  deployment_status:
jobs:
  audit-trigger:
    steps:
      name: Audit
      run: |
        echo "Deployment State: ${{ github.event.deployment_status.state }}"
        echo "URL: ${{ github.event.deployment_status.target_url }}"
  vercel-e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success' && contains(github.event.deployment_status.target_url, 'vercel-demo-wix-appointments') # TODO: change to your site name
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
    - name: Install dependencies
      run: yarn
    - name: Store Playwright's Version
      id: store-playwright-version
      run: |
        PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_OUTPUT
    - name: Cache Playwright Browsers for Playwright's Version
      id: cache-playwright-browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ steps.store-playwright-version.outputs.PLAYWRIGHT_VERSION }}
    - name: Setup Playwright
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: yarn playwright install --with-deps
    - name: Run E2E Tests on Vercel URL
      run: REMOTE_PROVIDER=vercel yarn e2e
      env:
        PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report-vercel
        path: playwright-report/
        retention-days: 10
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: screenshots-vercel
        path: tests/e2e/__screenshots__
        retention-days: 10
